# Generated by Django 4.0 on 2023-07-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=60, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=60, verbose_name='Şəbəkə adı')),
                ('social_icon', models.CharField(max_length=60, verbose_name='Şəbəkə ikonu')),
                ('social_link', models.URLField(verbose_name='Şəbəkə linki')),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Ünvan')),
                ('iframe_map', models.CharField(max_length=1500, verbose_name='Google map iframe')),
                ('email', models.ManyToManyField(to='parameters.Email', verbose_name='E-mail')),
                ('phone', models.ManyToManyField(to='parameters.Phone', verbose_name='Telefon')),
                ('social', models.ManyToManyField(to='parameters.Social', verbose_name='Sosial şəbəkə')),
            ],
        ),
    ]
