# Generated by Django 4.0 on 2023-07-15 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Məhsulun adı')),
                ('slag', models.SlugField(max_length=250, verbose_name='Məhsulun slaqı')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('packaging', models.CharField(max_length=250, verbose_name='Qablaşdırma')),
                ('consumption', models.CharField(max_length=250, verbose_name='Sərfiyyat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/product/%Y/%m/%d/', verbose_name='Şəkil')),
                ('status', models.CharField(default=('DF', 'Deaktiv'), max_length=2)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yerləçdirmə tarixi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Məhsulun kateqoriyası')),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-publish'], name='products_pr_publish_ffbfbe_idx'),
        ),
    ]
